services:
  - type: web
    name: trade-notion-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    repo: https://github.com/<ваш-username>/<ваш-репозиторій>